version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db:/data/db
  node-api:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./:/src
volumes:
  db:
    driver: local
  cache:
    driver: local
